name: mathviber
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - flask>=3.0.0
  - pip:
    - sympy>=1.12.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - ruff>=0.1.0
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.0.0
    - mypy>=1.5.0
    - pre-commit>=3.4.0
    - tox>=4.11.0
    - -e .
